language: java
jdk:
- openjdk8
services:
- docker
script:
- "./mvnw clean -B"
- "./mvnw verify -B"
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
before_deploy:
- chmod +x ./travis/*.sh
- "./deploy/before-deploy.sh"
deploy:
  provider: script
  script: "./travis/release.sh"
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: D76G8wjZQJ+uMJb2/ty4Dmc4Hq6yp0kI/Sx23pzxwIN48OW3ZUCb/Iq5tfo3uPmwHOmo23hRL+8xMQEwn+TnBoGnhVdQlX3bSRI0fD8N5Gqb37zEBikgwM9Eyq+J2Edzp+wJdsvOhhn41OZUo57A45got3k1jSLn3xhsgg+CP4iT8QYush7zNC9dY4Dn70dOD2gIpo8vcmVfePJ+TDfy5WHditTMBkZoIKHwpm6ZTRgXy/ZfFwmQsZxVAKtsPbkpfPCAS1SFY8AOQoPjkb3nZ43hehPl61q740gc+kYSb7FViVOITr5BRDOcSHTOh9pPWR6ZnQBvYaGDYxwDI688GllqScZyvwrlNMyeHpKLIrGof8D4cj2OAHCTDOd85Wj2SvDBNQOZgL1Tit5oq+E3bVoSSgi7sTNjGCJMmbt9bzZmuouErOwqxga27cawimpZU2vTUo32NjNPMKwoLuy0KhVtpdGbcsEmbxRE2zYDYE9InXaK0pV3xUWLtPE1zHbPb1mJhcglClV9kZsaliVxOuZ7clV2U7hfduDF+/uCY4nJYEtxfPPZiyslpUz82nVf2yRDV5I+djUpj1upARDd4/GR9cya71i7HIGRXJ/ZPSmAv/O+dpYNcMBwtj4AcXya6P5dG2a0GK92wj4D44hOqdYK7C0RS1lrVF17nXKZjYI=
  - secure: mZ7XW4VK4oU7Y5xjw2H1+Js6KnQxNGBfdXtbvhumttgyeXmEnvzvBA0NSlq7IdjfUDdxFXle7bwfZg+TXjAcb117kVUu4i+gESCIpp5u+g9xZhvmEcyWFoHHACmkTSqWX7vbwvrH1Xs/+EaCquDKiBYwDwKMvTbW+/K0CZCoBNSfbwwmeKAKQv011u8rp/3jZZAMli6p/SsgP6Dd0NtfsuuIdTV8lPPKvkt3D/g0zoGKKZ9919QOQp3J6e62MDoVjNnI96SKe8lgNagc0LqMAZZ3QaUEUOdbJH1jz9fMmtfTwe6+hpiJbvzlZzQpz5UPxfgWu6wnyjW8pXSHkSB7wJ1Rgty9xZp78Wl9npMugPoQCtLnS5SmpnfAl2nioKYcu6/ARrMIxPcFLEuEZ4CPgOnymKuqTutlvUjzPg9l/aGjbsDbo+TpqzolgpQhZijKeqzIofev17sux7mfjt7uq6IfvhcB9l7i2AoPZJQ8vxOfp9jAFCYHahZjRRHqlJpCGq3UaTZgjhJ4ugDpvPk4Yh38KMs6JDtdpG6NuqJCE/qG6JLkdxRVHYmI8yL2Yfu/egeJO5Gnh58K9s8FFIC6wsOwVS/YoFe/fSYttS4NQ1sHvqcSHuHS8iqy9i3jQ+d9RPoI1Y6AuGAVtM3Cn5YGFqo/bwr3kLOReanNQ1lJCQY=
  - secure: FRFfJAtWjno0Upo6yog34JaTKfzAxHgpsOfsipY3NUqa6joSOeDdsBEaOi1l6EyIHvbuDzp97VqIoY07CYPsOu/dSbN1qAc0kWsDerdVkx1yGrWfHjLseOcWfGuMRN1/CjdNdxLeh2Efp8PLece99CSG7WF9DAB3CIiOup0gG7QT9GKJxTYoVjolZxZYJIfc1fwMIGJHhWDeHkJXAO+qQYG7hWPaEu0IBjtHh8ApyeTga4Qj3Hwx1xbtjyvMUCwV4wDMzAkhC3b80ZVNLgKqUWPRQQ3PBhAIdZZz+hKzBPuzjD8PBJNUGjub3IIwwp1dRHPXaSGMLPs4thWj1sqf/yHHn2j2ArfRtByhi0SpCCAyGC73CnfDPhrYdckYZS2w70Wpu/cc6zFBirsdjIr0bCUp5hbk0D+tVS5VglevAblxdaazIxnoayGQ3QQIPSqVtDFsxCpAyi/nC9JyHEarJcPdVTNL621Zdp/TkhKiJ80ekf0Jo1PFv82rnRqr6J6TZRqyOkL4wCFnYkimBX8vFyV/tetaqD1YD8vfT5yqnapTc5cWBU9H2i7aOVML9M4Hgd4B3Mx4RyFqC7OPPAvQyOH61nZ+ex+E9Wr7T5jDsCNry30aSIPr/wtB8k6XVnC7sH9hcY5W9uDMJm679kdUqniFrWsLkVQdUO+QKcIejOw=
