language: java
jdk:
- openjdk8
- openjdk11
services:
- docker
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
  - "$HOME/.cache"
  - "$HOME/.gnupg"
  - "$TRAVIS_BUILD_DIR/target"
before_install: git fetch --unshallow
script: mvn -s .travis/settings.xml -Dsonar.login=$SONAR_LOGIN -Dsonar.projectKey=logback-elasticsearch-appender
  -Dsonar.host.url=$SONAR_HOST_URL clean verify dependencyCheck:check sonar:sonar -B
jobs:
  include:
  - stage: Deploy to bintray
    jdk: openjdk8
    script: skip
    if: branch = release
    deploy:
      provider: script
      script: chmod +x .travis/build.sh && .travis/build.sh
      on:
        branch: release
env:
  global:
  - GPG_DIR="`pwd`/gpg"
  - secure: 45anrAFZ48r82W61ZBmgAbyGh0ZTP7qJ8yl/qWWuLUWwTmYklmu1c5mX7fIao01KLBI8Cemx3FF9hHbJ2kSxiR1JetDHrcvfJGdWQs0+mApBnbKjJWKpAqhgazPzMGCVFrWvBnsFZmkq1vzYi9asF6DPIpVozHLYubokHQJPwZuQKCRI27g6o6QuVZjxBtR6njjnO77vNKe1ffiwRYXV57K2y6YnSgKOpiKvZOCoz6iJVinXLkPX28l3kSLOyOZ/vMiT+6AAcZZ7WoC7OVdIpUPcbNqJI/iD9UaREU4M3qPi0YYIUqD45atgfDoiPVnGawaIUf7mmbPKBhufcavFsTszuwP0D1HoxmATFctCLizCG2bhnLpdQ3uYwm3IL1xd2spYFF0DsyxXD3ga6oQOZT1mk3hItU+CuZBVF9Mw4+GQN7EGTQ3o9NssQ0jcyW8TMQYmXTDZl0oZZFWQIVXjCIiqrvcUe93Sg2zqF661BMlkxpQ58ExrE4vgofFZBdk76d8w6NJrD3s2FMilLnk0wS+CCNl0JRY5nQZ6tWSj4qazSJhI+xkkuHe5Uk6GuXgBcgkMGSXyQ09Nj73CNduXhnNX9tDj+0tBOiMPRSNxq5WlWJnDMKFdkpUIHeNa0pAtTJKNjo1CR4V9EOXwrc13Ycrgfq495LrMCP15futBVwg=
  - secure: MQloMaR3YGUKd+7e89NJpQcnFvKNZb6z/zsyouZTuqHAxvu/38yti3E714ev62DhTKi/pq0gfzNXWRbDHn/5ubApsCtaPdkbJAZPPVKFT+mm3VuZ2Rzo4YJhPqXvZ3wf2CEwvvra9E4Q4P/MNtFlA/DiXJty7Gpsih2+zSyHzkjJe774PeR3//vGpZ70lZIn2iniYWCMliBztVQCRs7osKEsdscbIJaIWsvEIo83EaqJo1eG0iMatwcsbCDWltnpR6wrpW2jO0bPW+flBYX8+GreTWkc3FpL3P+/3QAsaN/UGrF5sx7WDU8rVQvXJsNGDsO0FPoxpVsGe8HZ+1aIEywgiCWrtRl++yuMFvodw7WjykEn8iYbUH4oLIb+EZ5c0gRkwWHIxRoQJHmaSJRWmz14fW8pBxM9gQnnNLvbBv6ARPN9ekKNoJSGpvYvUyt40yJWJfzOBz8PM8WfvvTuMz4NX1GmnHmf24nM4hD4RZmPNPAxGf/t5BZhPXHYzNw9YR6bexC1MgMfmrERrf2H6S1zrV/QpBs7RyCqz4VYamf+ORoEBv4nWGYCwkmapL3U+XfyBZUOGcSSvKgahjXL7XM65lSSp1GsY/W8Lb4/eo6y7iGCpK+HB3GiyImjYTl7VggzYVKlhvgwSRU6aZZV16A+u4ASuDbu8ycmEdUqe9w=
  - secure: Hvpo1/HwKUzEt4nrMwEeSCikbLZsC7VUi375GSvSP3nPR6+JrWUUScr9qJM5hkJmPO0oKWqvzwZLSUM6OJNVKSC0oehO4pKrJ62d2y3AyapoWsLWf67cJgh/HPbxPfCeJcxsqn0L/eN2NMTR/f0Xg0eZkVNuyavJJmhCMRbqNff1oPGgXVvD0YkSJ1orMLeS59VzmoB9TEc8Ty5upiKxie3lkhdF+3rXyexRg5yf0f/WTdKnaajEnbtZRFi8xWzIUBvBGcbgU3eaeH48wYMbssnSK9ADLrsqAGSM0VjLtQY6jcVQM5VFbbRGE3eWLNsKtahrxU26waJfDlhqFoBcHsSCYNQRe7tDN91d8B2i7tVkBgPiUKKSdUG0KiIX0hpUkx36CBu24eYWDIk2HNwVygKO0sVt93v1RunNxHy2dkCYYTmV1fN39jslgSP1dbdCIlN6pv0HCkHjc2PypNdtGV2ore5tICrKmaKF/fHcGGmHQ8x871K+xRmwIoRTkLWUiYi2B/vHr9mXEbORQV0ImydPeXXLkAkxtgMRrAbfYrPYFUoP/y69uAapqEdqOnG1lfIQ8BFSDrOgxk41ZmVXYLPgJJtyPSXfLIfCgbxGXqOjQpRD1e4wYktKnn/Ewppk6/11wSd0n/k3KsftEXsCKRwDdO1OBVDJfyuy2nQFcCo=
  - secure: iLPpz/I/+W+b4hzk98Be5lX1bPsS4PV4x7GlYLubmGKBZJH1qRkONeOTkHC5gti7m2MdAAjCHCt24CYf3uhah0ru37C7EG53BqVacV/IdT90O5To6yla5OYAH2YH6HE09aUF9UoPQ4+xFBtkknqso28BC4VRPKP0qNJNuVO6CTN4KpHNOLm/Q7+fi0B9rOopXcCnBODZ7ZG4pgIqGmUNSB4Gxr4V3r3UOEDaDLoXSeXciCx4rfUaEHQaszRnO362v8vXlhARsDLFROFvDSclkGmnmKaNTT2UHPHVzH96CVVmnS9yIt8MbESLGBhGeQnMZOeyQxNXKMMe6Aeg9IeKrGa7kuGraeHwVeFzDc2p+pRGdBFaMCR0Npf7SlDwU7c1l0MfWxQ0ExSJ1b0QgHUKQzeIBA91eg+DRQokwhDE7Bbo2rcfQ3UfDSz4ThHIq4I+r7edARiGBGiSuwFH1F9TLqtJJ0tHVgrb8nwjn1SWQGaX0VRpbfdLte+TURKSAnDaLJSYWz7hktDF6jHWx/b8eQC4ZiNf1141FTTTAz6/RKcRsvZeC8LtX8nqk1Bjz+4JD8+uo2SDzrDPRiXxWk66bGDWOOCliEB5ua7yIT+HoyA9BpZAvZV43Y5yhNTedccIoezN/43Tjwj/azYRTODrfHusS/HwhwHSxnLUgKmPDBg=
  - secure: x4DyqZ1HxmtEmxafN5koqinw8Ce0SmB06euiqLZfMZV6xwLaGepjEUV4DVmEur/jyabMZZqcLoQdP3p7Altg7zu0ToGuO5sxm/76Mhx4Bh9E7uM5g/wDRU8/Ef5SIIvqHL0k2G63k5Q4ukjP1sg/QIin7+Um86Rlpm9GzfGZZMD5FTjuuZE8Do4HaplNgemNX38Rmvv0CsORSc4chEsV7linfEj80yuZ4Q4CBioLRolm+tx8sju6j9GbqANvxMUWrATWHCAt2iEVyEYgeOZBtITjvXoTohZjWEMEwqiRW8LKGQkPBlUJWWyPpKgZ9896lMVkEndda6qgCOp0j9rdnK2h4oqWcu9KpgpMhPJ+eD0KxYhAlPDoX10eTN8jCJGrktnBoy4ubPkNjxr9v7Vak39C6CIckxIl+eXrd6AiKKxU5cD+HVSRFok+OQ/udRGo512+Y2ZdwMgz/70RBHbuscZ3Ou039cqw01OOBrA024sndgSvvzz1r+1xI82gIB53MzxQnAz6a+T76jiOOWMZMeYzLiBE77Ze6Q38OztfmHBaP4/8ULjTY63eBt58DHZmb7+x3ixL5gMQkEIQxA0nysDoBY588497eiHn3WO0R/EQ/B8eBnquqC5GhoujbxrDPfgdnMftxAYkkC0wlA2ZZkWeRaWw8vwpjiLFmNwLlyM=
