language: java
jdk:
- openjdk8
services:
- docker
script:
- "./mvnw clean -B"
- "./mvnw verify -B"
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
before_deploy:
- mkdir -p ${GPG_DIR}
- openssl aes-256-cbc -K $encrypted_f3cb6cb238ed_key -iv $encrypted_f3cb6cb238ed_iv
  -in deploy/signingkey.asc.enc -out ${GPG_DIR}/signingkey.asc -d
- gpg2 --keyring=${GPG_DIR}/pubring.gpg --no-default-keyring --import deploy/signingkey.asc
- gpg2 --allow-secret-key-import --keyring=${GPG_DIR}/secring.gpg --no-default-keyring --import deploy/signingkey.asc
deploy:
  provider: script
  script: chmod +x ./travis/release.sh && ./travis/release.sh
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
env:
  global:
  - GPG_DIR="`pwd`/target/gpg"
  - secure: QszIUbBw2EHo2w2SNXTZCV7Dp4hU5vwA6YDZrcACAjXoOeNnYivp7ZBHPe3xj/UFp/vsPP88uWftB4lVLpgp1pHHSF7ggl8rgRlMuiUxUU/UtmuppNXFGip5T2PfEXRfdmj1pAWbN2t9x8TVcBEWpokOaFV1V4CmVN2o++F4QTAeFVd83+t6oidfWLc9Zz9+/nJHjvz9ih7ji6PYgLZnU+086mZGTDF0Y12Y3XgiBUzPdiPt1iFnMGtvT1U9EhWp4UlnUKwXSH+IVsRpie49XdJORWkEw8iSYDJDaoIqT3n2oag409gnEu9C8aGY2ECQG22MDk5WmHmhty2KI4G46GD+97PmwDQ3QqAPz/mXygpJ7CRHGYJ7cCCkFYuqZpfOZA6CvG9wOJoHet6Fa7ZaKX305K31CA0i04GauxK7d2A0b8dHbcunFWLBu26T/0KHmTjGhNvs4xonS2IWKxAIXjXoBB0sMOfsXGVgv6mRm2uv0jvKejrMWSVXuEEk8MhmEVh695ywqOe4TQobZxyc8R7RiNxfR0nNPG0uziltC3STbrBO0z7+aQaKvTvQO0dcFQgcqPzCESOQSAIz/PHJGJJFo3piqduUAnbBi4RcuM8pkxKxKEAWypYMlEUuwog1TQppiLQRiLdnh1jmsGEQPC/VQsYCE8B/fKUrXv6MZOk=
  - secure: u6hvCyydEvjkpaETx+6lKBgrypDe5AtlQNTD6r7S/twRY5arpEsn8F55O1IuLVe4tXM1rvmH3z22e3K62yXmehpFrgmIe7Gqb9EWw/RwUGC49fcPj8XJYAHuLpV9ifgy1y+1juJFa3CcSBFeO49NBxG0SDDVbLa9YU+oAI/819qDqqaqKhhsd5dPFw0TjD0jeUxrcL2CWSvBA4U4jvqQEIG7RgWQpyN5nqSUgqLGjoGYL5JK9gqdRoj0pWiyFopFjQPiryUF+xyHsmNCO+eqjyxF3HUQ3A7PAlIDF/anvP37Db6r8V5SFwZaCK97noG9vkcIclIAGXWH62wHPLibKrS9SIk5Lxg1RpOC9Pv2k4TKlkwsEb/VEAqtFTH6TOaFwThXwkNC36JutuQ860LDlzva8390YiFjAf75hh+HCw1qOPZbrK8qvhf+PguGbpCSl0a+zpskZw+01G/WlvXWpegKFaYPm1eJ/hbacnpBUm/crcWl8u0wQuwLzepSLPBMCJ6zn62MSCyabZ7AO9DelMFS5z5nWzCzmzDrj3qWxO260EiFiLDO+x/6jJBe/VMJgdBg3I2qB9dZ5i4OSdHbBSCCDgf4ETb1B6gyz5akaRGzZ45j0LXWE+s/Xl4iPlqq6k80o+fPSYhHRnndKgPgcLZArmeLORDlt6Uaj3TFUPY=
