language: java
jdk:
- openjdk8
services:
- docker
script:
- "./mvnw clean -B"
- "./mvnw verify -B"
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
before_deploy:
- openssl aes-256-cbc -K $encrypted_f3cb6cb238ed_key -iv $encrypted_f3cb6cb238ed_iv
  -in deploy/signingkey.asc.enc -out deploy/signingkey.asc -d
- gpg2 --keyring=${GPG_DIR}/pubring.gpg --no-default-keyring --import deploy/signingkey.asc
- gpg2 --allow-secret-key-import --keyring=${GPG_DIR}/secring.gpg --no-default-keyring
  --import deploy/signingkey.asc
deploy:
  provider: script
  script: chmod +x ./travis/release.sh && ./travis/release.sh
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
env:
  global:
  - GPG_DIR="`pwd`/deploy"
  - secure: VwYoxtSuMD8g44WqQ46GM9/gU0DQ00BVBd3CSwZtorVyZST5vJjIQKfQWqwLGN58ssJifyEPtF2l27oiRcCv1vJD4NQhLVlsqvPnt2gWSmindiMw4z6JZYWYSE7dQmEn2PmFKsZLtARStUD1sXrgr147h/DTYxn1hJ8vOxQ51JVHUz3tzSLM78PWWO/5iGpTV1ERe9kplNJy6NcRr4L5Xygjv8vpMDYhdXX1E441kxO4EPQ8IicaZet1RcPFFi36kx1VUP1xyMW32jCMOCKpy3eAXpphTVU6xueX0DxGXIU7CSNtnbwdQ3n/g1AHYb5xNjz/cBfvetQehx8y2dpo/pl9LC0f8/MeC1QuZU1uSuB5kvrbEnZWP0jXE+M6WkPehzAn6M3/3YiiyfcPrLhjv7mXqGf0+hISLSjHc3fGzvgmeIJP89ZgA0ySJUEYgkvp3ecToDMfhZDWRD8eSWgo7XaKREluwntTtDl2ss9NE8QEA6OULfDB6zmOJZzS8SHuRNuDU8Abtpy0Axa+g3AljDhh3uiu6mIHicf6UtCbKpvfoCxoOb41l0yXmqa8m7l0/UtJCUv/iSy6fVFV4f3hp7R4pe9Hkaa09DiLp2KdOwDtC8r5Tpgf9HfRV4JolqQVA9mkMRastW1Myaq4uE/cKoTd53UAOYI5tGCPSIQ3j48=
  - secure: AWpkDx8GQLyCTQ9urLCwACabE3pCKWmpObd6wMeDItovwnb+nYcxy3ZhX2wm0/LYPxZp+sAZkhAGO8i3aKiVoI9G6EYW6tFDAW1mGO/VQmy254lyjIuPQHFhVPpwVZwagC/Fluw7UV0YD1TNT3o5kib+f02yHKvvk1/SmWnU0vTOf2LN0wYaB8xpzxjjqSLYTl0Q2Gp/ZFy67riUIn0VvgeAAfHIiiAAwinCmL8tgaGqlvni+pJCk68yCOqx0heaHeBUOXE6q5P6ECHfiC1HxvYsMmHrGmqjTDryGq+BoDmee4n1x6rmb4fJFd1uMV7i8Ap3qxBGKAugJVQIhVjNHPTwU3to+2aLInR5+BXM+LJBpTORV8MCBszAUGj3RDyGHmu6RFtGXMKGJzlGrM6Y99UDKp38XClT2rAIaVSV9oFrZUH3HIvFM2NfVhFIsN9tbPg8eMGTfo3nTl/rbkCrU+xrfB+59nLPmqyl6fmu19X/huhPBje4rJkC6++UlHcbnWbbOQ83MP4YgHyfC37nArPpYpJJHEsV01LhWn6R68bBE36XiumWufHQfTHhddaky83zxc4OBOWFXCi26AxPzmu81ZE+xz0phyrNjHgTASrMY7P0NDTzhM9HWi5xHAxwta42P4zIDNRELoPt1zMB+24nNvrQePJGNGIRhGmffQo=
  - secure: ZTvouqkNCMJ3d8Zl/vlISjVii1eOuPXjvF/FunKxq0zLMuMurMHwsUdq0NOcsqTb2aXJEs8H0wimu/XUZOLoD0Lo7zrpaYwUyDqaSnjX5TSB7zzW0zA2nqiyy/2Nq6x3u42mwnp2W2rqpF1N7bLdkVc9rHITV39I3NG00VeA1L70hdYAHajTnVm19lemsaXdSG23mxOLpqQGaGNMRYOvwO0nTInFFsxBf5GAiR0PEhm44bg2rt2XBv7iirDy6DAr3kW2ye3/IsJG/XYw+nlmDmHSJRD1ON7WotFviAe4SWzD0E5VQLPY3oty8d0sWdMJitZktuMx/hoTAb+WjnRDOICLkHw9JyzAfAo5CTr3fKoL2SdrYpVI78lraIyLXhff9E+//i0zG43QAOFXMm/huQ0kGGnArdbYYWrjeba60lfpFzaED3GfqihnGkzjg+6JSew/e4pTMw9T9pQC0E8Tv0N2bGayEx6iAvb8Np/8WyA09QX6AtSmDR0hD0ZMeBkiPhuw4xtWVPL0aZ7X2txskMsr8xphLW87+/ykm0j2HCxAq07mJ3tWc4slPRwzCAzeMA8ZBBG5FT7CuD4E2/gpzpyy01XJ7aO18c3GHqKqStZrupln9ER+c3gtnghAEzAgK4SCYEGDz8sGXoBdxWtoRnryusFVJIZNnFzxotWu3sI=
