language: java
jdk:
- openjdk8
services:
- docker
script:
- "./mvnw clean -B"
- "./mvnw verify -B"
cache:
  directories:
  - "$HOME/.cache"
  - "$HOME/.m2"
before_deploy:
- mkdir -p ${GPG_DIR}
- openssl aes-256-cbc -K $encrypted_f3cb6cb238ed_key -iv $encrypted_f3cb6cb238ed_iv
  -in deploy/signingkey.asc.enc -out ${GPG_DIR}/signingkey.asc -d
- gpg2 --keyring=${GPG_DIR}/pubring.gpg --no-default-keyring --import ${GPG_DIR}/signingkey.asc
- gpg2 --allow-secret-key-import --keyring=${GPG_DIR}/secring.gpg --no-default-keyring
  --import ${GPG_DIR}/signingkey.asc
deploy:
  provider: script
  script: chmod +x ./travis/release.sh && ./travis/release.sh
  skip_cleanup: true
  on:
    tags: true
    jdk: openjdk8
env:
  global:
  - GPG_DIR="`pwd`/target/gpg"
  - secure: L0NkjtNBxVelf/cb0LH0rCKhTvWgZQFrBqPKDUQZWKrv8+PwecpzC3B+Eq0l4NrV2NpRJDEOloYYWJv9JoDRzxuOPtUnpelGxmwUe3WQqtNG/5IJ4qS6WM7luk0xzbGkEPQiPuFa8IloXgX0yZiPZZvhZa55YVoX9De9NtIOAJShEcX6NZH1Y1mACaL9YODGkbmiVDXL4qMIflKiBzVUjjKPpa84JKDhv414Q04gBbAzO2/IM585BUUTAkSEOj0SN5Nm6gnX7RFs8sqBnON3SNQym9z1t/fNXJfzgoTJ6A+JU+SqufRunBlNEnd+Gns6MEARHG5Gk3oDRtG9UlxC1iE4WmdDYipdxdwTro0QhzSQDvu2Enj4I8AgMfEKtfBJnc+4bU9zewc/uZlZOStAn9zp9cH1qfUmhCWn6XfDnoCYPCApwIefTLSKBG/wvhq54tzGbGvsNOnCNVBYQRTSvIDg6DEJLIzZoHM74p16XZMeR8LQRvXBluAeaSOrOBhuVHKsH/jW/fEY+y/cV8CdcToVHO9uLeECmiIQJyeKRRk8ZUpzPMB+bMGfRLaPBKQP1ZBqafZgT5ycVpjqk5Nm5mKZtJmQn7BK9G4XKSbse2/aTretdpQ4/C8DqfrbDX3Mg+RPXWR+JGu9h065hJWdcvUKTtkwGf0sIV2SpqxXId8=
  - secure: IXYbInJ9jcyMewfnyPDMTOqMKehhSXmnz8FTSsVi2GW6N+hId2uXMlZA3hHiJrMDAAX9gnpQFd9uwg5LVHn/I4cTj54g88v+WHcFrokVtRE3/zRvypIHruxFFALQwTD4RCRjH5+68pzG2Idpqpg6T4YI9Kgmvz2X7BVf2MC9rWu8u7k9MpkmaRIiVDQKWmI47QQtf9t/x5+n8vzbOysdlBB93c8V+gSP0wVDsWknXOKLXvA7G5oF2Up/ZyU3iXlSWvfa7rD6hhMPTumWUOiDr2++pKVubfMve4gA5yWEMaqdS0RSF9BEOD8BMtW0KeNT/oxsFVNrSt5VI2I/L849BhJ59LmXx1+eFnISVS6g3A4EKQXa1QKXh13MdlJXM9tvsOQt1iBQE59ZVHFokP6dbSDVW/lQo/JdFxNyn6hpuY48FBntpw0bDrDesjkU2BU1vZNvP93+Hj5nWcxxvDA3CaEJQcoySeNmPQmA+ZdI7VYIWen3h/fi5gVUApB1rIiBagJbsX6IDDPaMD4hTUZ6HGb3/XPELRAUs6THPkBPwaRijYK7LeZlBsI4csm9/nTJpkd5fSC1DHp1Cax5P9mn5J56lkaElxLX6hl5D2vK9IIygQSFxiEgkouqTdbWc4WA5w1x5qlo0lhLLe9/ioI1eHq1Kq4URBZ/V/gbP0GVbIM=
