language: java
jdk:
- openjdk8
services:
- docker
script:
- "./mvnw clean -B"
- "./mvnw verify -B"
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -B
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: UpV7VB5MX2+gtMotT6GXJNJk77jt0aNDuoHsl1uPoOTrk6eieG7WtT1sRXmZpnJpAn77z6Q0y6bo14fxFHcMXFaEuGDIvK0rPEeLFMuvp3OQHUjkmvM553iQ7uu+bq9bvi3oyddbwDo4GxZ3ktSHt+uqA8KZL3/Ts/N8TLDHDYrUnCx5G4hbFp/rSvafxXjmXZfjF2FjMGrSQjkANUSow7GDNqOdj7k917AN6IHepbGIB5yzgXIeaWbNxGknRZTnMUAEDQa5JV6e8ydxlpMbIiotL62aoirpmX0Ib0RtefftHZDhu35rQFU0ZMK5SBY0ecMUypV9NPClrbBJzu2uqMN4lCbukPcAZSQRQZfNXkf9NJxHnKNZVODEuCDKCklnNMENwBpgnU6h0ou9i2ctS0gJ7KNcp/A3is61Qv8Vm+lLvGxu2IiSRKcOHfn3YSOi6YmqVJe5hgPb24yWrf1FXfUawgDHY2IleQfbfDR56GKjT07k98Qd38EmlnMzHH9B59EnDURJxYCYh3N7ODwK9raKPZWaL4IXkIOyYG178ZR7ZVqvAFHCKqvocjlgnSXJ1VoxWDYKspMIdvRhjvT8GI2jByT16TK61W4j9+0PbR+ci0hiU1p7DJ/xRomEmyYKMGiIN8mAM8Hzz3JB9y9RFMjg9bhH/Nt6WeZYpz3yzRk=
  - secure: qsnqMTVh4bVR1YJ4LkP9zB/mXiaXoOn+bzMjQqHMWnz5JhP+8xwlo4rux2IHenOYPZ+B+OWEYlNNEhOiVort/BCnUBHONANAtT3JQ1VIakbYVLqtyEjZFRgYXIrfoLrWtW6bbHddMdJTAq077e5CUdPptODJYqLkhnQsddNE7kMOIVTPHxlmpf5hX+U/9QQfJWm9AcwjdQMbKmv82cBY2pWaaQ/rSLCloTZoMoZ91t8u9s9F9wdCOuVu9UwqhaMe771Zy8EbF3tui6cd5AX11dG/n6aDJAa2TX0oVPOGD+0mjMnLS8F+HGwo6j0c/XoBpZ7wNBjbF0SxyU7dJ9Gfb9Dz16TsP9CvgysJFyUeMih45WOqBUJWCw6UG1mtt9gXEuXhVSQwQPB/fHXopDdtaib/coUgsmsudXNK5FZ7WnhJCYAHlV+Gabv3pCOF0xVfONQ1BBOC0WzhaiyVEHPDgyeDv6aMNrrq0PdZQvcfYJ0OhWaAhEcRnIb3jKDdpnXkhVHLQ4mSM7+TS7d65t9GwkTYhNFgI2uimsO8CuHk7Ns6LlVhzEFiKN6TPAsnjluxjtSlefLQDHKH9VvBRiNHt0axcAV4Ezlo7m1lK3Pd0lqxNxyyFolFCscY/gCxJ6Gc8pcGRUobPWO9nVqDuGlm1xV4c+ed/1LWWGBvrFABnok=
